### ISSUE TITLE
Feedback of the Frontend from Group I

### ISSUE THREAD

**Issue by Arklaide** [itu-devops2022/itu-devops#23]
Hey guys

Sorry for the big delay, we were occupied and totally forgot.

- [x] Do you see a public timeline?
- [x] Does the public timeline show messages that the application received from the simulator? **Yes, it shows very new data**
- [x] Can you create a new user?
- [x] Can you login as a new user? **Works perfect, however, the login page says sign up, no big problem**
- [x] Can you write a message?
- [x] After publishing a message, does it appear on you private timeline?
- [x] Can you follow another user?

Everything looks great and classic and works fine ;) - Good job

**Comment by HolgerGottChristensen** [comment]
Thank you for the feedback :)
